name: build

on:
  push:
    branches:
      - main
      - /^\d+\.\d+\.x$/
  pull_request:
    branches:
      - main
      - /^\d+\.\d+\.x$/

env:
  TZ: "Europe/Brussels"
  NODEJS_VERSION: "20"
  NPM_VERSION: "10.x"
  LOGS_DIR: /tmp/mdi-ts/logs
  LOGS_FILE: /tmp/mdi-ts/logs/build-perf.log
  HUSKY: 0

jobs:
  build:
    name: Build and Pack
    runs-on: "ubuntu-latest"
    steps:
      - name: Set environment variable 'IS_MAIN_ENVIRONMENT'
        run: |
          if [[ '${{ matrix.node_version }}' == '${{ env.NODEJS_VERSION }}' ]] && [[ '${{ matrix.os }}' == 'ubuntu-latest' ]]; then
            echo "IS_MAIN_ENVIRONMENT=1" >> $GITHUB_ENV
          else
            echo "IS_MAIN_ENVIRONMENT=0" >> $GITHUB_ENV
          fi  

      # See: https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v4

      # See: https://github.com/marketplace/actions/setup-node-js-environment
      - name: Setup Node.js ${{ env.NODEJS_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODEJS_VERSION }}

      # See: https://github.com/marketplace/actions/cache
      # See doc: https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows
      - name: Cache node modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules-${{ matrix.node_version }}-${{ matrix.os }}
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Get tag name if exists
        run: |
          TAG_NAME=$(echo $GITHUB_REF | sed -n "s/^refs\/tags\/\(\S*\).*$/\1/p")
          echo "GH_ACTIONS_TAG=${TAG_NAME}" >> $GITHUB_ENV

      - name: Install npm ${{ env.NPM_VERSION }}
        run: npm i -g npm@${{ env.NPM_VERSION }}

      - name: List main variables
        run: |
          echo "Commit SHA  : ${GITHUB_SHA}"
          echo "Tag name    : ${{ env.GH_ACTIONS_TAG }}"
          echo "Reference   : ${GITHUB_REF}"
          echo "Head branch : ${GITHUB_HEAD_REF}"
          echo "Base branch : ${GITHUB_BASE_REF}"
          echo "Build number: ${GITHUB_RUN_NUMBER}"
          echo "Repository  : ${GITHUB_REPOSITORY}"
          echo "Event       : ${GITHUB_EVENT_NAME}"
          echo "Author      : ${GITHUB_ACTOR}"
          echo "Main ENV    : ${{ env.IS_MAIN_ENVIRONMENT }}"
          NODE_VERSION="$(node -v)"
          echo "Node version: $NODE_VERSION"

      - name: Create file & folder for GitHub Actions logs
        run: |
          # cfr scripts/_ghactions-group.sh
          mkdir -p $LOGS_DIR
          touch $LOGS_FILE

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build

      # See: https://github.com/marketplace/actions/upload-a-build-artifact
      - uses: actions/upload-artifact@v4
        with:
          name: mdi-ts-dist-${{ github.run_id }}
          path: dist

      - name: Save logs
        run: bash ./scripts/ci/print-logs.sh

  release:
    name: Release
    runs-on: "ubuntu-latest"
    needs: build-test
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      # See: https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v4

      # See: https://github.com/marketplace/actions/setup-node-js-environment
      - name: Use Node.js ${{ env.NODEJS_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODEJS_VERSION }}

      - name: Install npm ${{ env.NPM_VERSION }}
        run: npm i -g npm@${{ env.NPM_VERSION }}

      # See: https://github.com/marketplace/actions/download-a-build-artifact
      - uses: actions/download-artifact@v4
        with:
          name: mdi-ts-dist-${{ github.run_id }}
          path: dist

      - name: Create file & folder for GitHub Actions logs
        run: |
          # cfr scripts/_ghactions-group.sh
          mkdir -p $LOGS_DIR
          touch $LOGS_FILE

      # This ensures that we are authenticated without requiring to have an actual .npmrc file within the project
      - name: Set npm token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      - name: Release
        run: npm run release:publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Save logs
        run: bash ./scripts/ci/print-logs.sh